// Consistency test proving `permission_guard.dart` matches the backend
// permission matrix (closure of remediation blockers F1–F3).
//
// Pure Dart test — no widget binding. The fixture is generated by the
// backend repo (`Calculator logistica`) via
// `scripts/export_permission_matrix.py` and copied into
// `test/test_vectors/permission_matrix.json` (blueprint §13.4).

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import 'package:operion_mobile/core/auth/permission_guard.dart';
import 'package:operion_mobile/core/auth/user_role.dart';

// flutter test runs with the package root (mobile/) as cwd.
const _fixturePath = 'test/test_vectors/permission_matrix.json';

void main() {
  final fixture = jsonDecode(
    File(_fixturePath).readAsStringSync(),
  ) as List<dynamic>;

  final fixturePermissionNames = <String>{
    for (final raw in fixture)
      (raw as Map<String, dynamic>)['permission'] as String,
  };

  final fixtureAllowed = <UserRole, Set<String>>{
    for (final role in UserRole.values) role: <String>{},
  };
  for (final raw in fixture) {
    final entry = raw as Map<String, dynamic>;
    final role = userRoleFromString(entry['role'] as String);
    if (entry['expected_allowed'] as bool == true) {
      fixtureAllowed[role]!.add(entry['permission'] as String);
    }
  }

  group('permission_guard vs permission_matrix.json', () {
    test('every Dart Permission constant exists in the fixture', () {
      for (final name in Permissions.all) {
        expect(
          fixturePermissionNames,
          contains(name),
          reason: 'Permissions.$name has no matching backend can_* method',
        );
      }
    });

    test('the Dart per-role matrix matches the fixture for all 4 roles', () {
      for (final role in UserRole.values) {
        final expected = fixtureAllowed[role]!;
        final actual = permissionsByRole[role] ?? const <Permission>{};
        expect(
          actual,
          expected,
          reason: 'permissionsByRole[$role] drifted from permission_matrix.json',
        );
        expect(
          expected,
          actual,
          reason: 'fixture grants permissions for $role missing in Dart matrix',
        );
      }
    });

    test('count sanity: 34 constants, 136 fixture entries', () {
      expect(Permissions.all.length, 34);
      expect(fixturePermissionNames.length, 34);
      expect(fixture.length, 136);
    });
  });
}
