// Financial-parity tests for the mobile invoice calculation core.
//
// Proves the Dart implementation is byte-identical to the desktop
// `services/invoicing/service.py::_calculate_line_items` (banker's rounding,
// stepwise rounding, qty-or-1.0, discount precedence/cap, pre-set overrides,
// sequential sums). The fixture is generated by the desktop repo and copied
// into `test/test_vectors/invoice_calculations.json` (blueprint §13.4).
//
// Plain `expect(actual, expected)` on doubles is the point: bit-for-bit
// equality (no approx matchers).

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import 'package:operion_mobile/features/invoicing/logic/invoice_calculation.dart';

// flutter test runs with the package root (mobile/) as cwd.
const _fixturePath = 'test/test_vectors/invoice_calculations.json';

/// Converts a JSON number (int or double) to a double without magic.
double _d(Object? raw) => (raw as num).toDouble();

void main() {
  final fixture = jsonDecode(
    File(_fixturePath).readAsStringSync(),
  ) as List<dynamic>;

  group('invoice_calculations.json vectors', () {
    for (final (index, raw) in fixture.indexed) {
      final entry = raw as Map<String, dynamic>;
      final inputJson = entry['input'] as Map<String, dynamic>;
      final expected = entry['expected'] as Map<String, dynamic>;
      final expectedLines =
          (expected['lines'] as List<dynamic>).cast<Map<String, dynamic>>();

      test('entry $index: ${inputJson['description']}', () {
        final result =
            calculateInvoiceLines([InvoiceLineCalcInput.fromJson(inputJson)]);

        expect(result.lines.length, expectedLines.length);
        for (var i = 0; i < expectedLines.length; i++) {
          final actual = result.lines[i];
          final exp = expectedLines[i];

          // Exact string + unit_of_measure assertions.
          expect(actual.description, exp['description']);
          expect(actual.unitOfMeasure, exp['unit_of_measure']);

          // Exact double equality on every numeric field.
          expect(actual.quantity, _d(exp['quantity']));
          expect(actual.unitPrice, _d(exp['unit_price']));
          expect(actual.discountPercent, _d(exp['discount_percent']));
          expect(actual.discountAmount, _d(exp['discount_amount']));
          expect(actual.taxableAmount, _d(exp['taxable_amount']));
          expect(actual.vatRate, _d(exp['vat_rate']));
          expect(actual.vatAmount, _d(exp['vat_amount']));
          expect(actual.lineTotal, _d(exp['line_total']));

          // Desktop keeps total_net null.
          expect(actual.totalNet, isNull);
        }

        // The 3 aggregates.
        expect(result.subtotalNet, _d(expected['subtotal_net']));
        expect(result.totalVat, _d(expected['total_vat']));
        expect(result.totalGross, _d(expected['total_gross']));
      });
    }

    test('fixture has exactly 29 entries', () {
      expect(fixture.length, 29);
    });
  });

  group('round2 — Python banker\'s rounding', () {
    test('exact tie 0.125 rounds down to 0.12 (even)', () {
      expect(round2(0.125), 0.12);
    });

    test('exact tie -0.125 rounds to -0.12 (even by magnitude)', () {
      expect(round2(-0.125), -0.12);
    });

    test('2.675 rounds to 2.67 (stored double is below 2.675)', () {
      expect(round2(2.675), 2.67);
    });

    test('3 * 0.005 rounds to 0.01 (false-tie case: exact value < 0.015)', () {
      // 3 * 0.005 * 100 == 1.5 exactly, yet Python round(3 * 0.005, 2) == 0.01
      // because round() operates on the exact binary value (1.4999999…).
      expect(round2(3 * 0.005), 0.01);
    });
  });

  group('behavior — coalescing, overrides, aggregates', () {
    test('zero quantity is treated as 1.0', () {
      final result = calculateInvoiceLines([
        const InvoiceLineCalcInput(
          description: 'zero qty',
          quantity: 0,
          unitPrice: 100.0,
          vatRate: 19.0,
        ),
      ]);
      expect(result.lines.single.quantity, 1.0);
      expect(result.lines.single.taxableAmount, 100.0);
      expect(result.lines.single.vatAmount, 19.0);
      expect(result.lines.single.lineTotal, 119.0);
    });

    test('null quantity is treated as 1.0 and unit_of_measure defaults to buc',
        () {
      final result = calculateInvoiceLines([
        const InvoiceLineCalcInput(
          description: 'null qty',
          unitPrice: 50.0,
          vatRate: 19.0,
        ),
      ]);
      expect(result.lines.single.quantity, 1.0);
      expect(result.lines.single.unitOfMeasure, 'buc');
      expect(result.lines.single.taxableAmount, 50.0);
    });

    test('discount_amount above gross is capped at gross', () {
      final result = calculateInvoiceLines([
        const InvoiceLineCalcInput(
          description: 'cap',
          quantity: 1,
          unitPrice: 100.0,
          discountAmount: 500.0,
          vatRate: 19.0,
        ),
      ]);
      final line = result.lines.single;
      expect(line.discountAmount, 100.0);
      expect(line.taxableAmount, 0.0);
      expect(line.vatAmount, 0.0);
      expect(line.lineTotal, 0.0);
    });

    test('explicit taxable_amount override is respected', () {
      final result = calculateInvoiceLines([
        const InvoiceLineCalcInput(
          description: 'override',
          quantity: 2,
          unitPrice: 100.0,
          taxableAmount: 150.0, // NOT 200.0
          vatRate: 19.0,
        ),
      ]);
      final line = result.lines.single;
      expect(line.taxableAmount, 150.0);
      expect(line.vatAmount, 28.5);
      expect(line.lineTotal, 178.5);
    });

    test('multi-line aggregates are sequential sums in input order', () {
      final result = calculateInvoiceLines([
        const InvoiceLineCalcInput(
          description: 'line A',
          quantity: 3,
          unitPrice: 0.005, // gross 0.01
          vatRate: 19.0, // vat 0.0
        ),
        const InvoiceLineCalcInput(
          description: 'line B',
          quantity: 1,
          unitPrice: 100.0, // taxable 100.0
          vatRate: 19.0, // vat 19.0
        ),
        const InvoiceLineCalcInput(
          description: 'line C',
          quantity: 1,
          unitPrice: 10.0,
          discountPercent: 50, // discount 5.0, taxable 5.0
          vatRate: 5.0, // vat 0.25
        ),
      ]);
      expect(result.lines, hasLength(3));
      expect(result.subtotalNet, 105.01);
      expect(result.totalVat, 19.25);
      expect(result.totalGross, 124.26);
    });
  });
}
